import type { ThresholdSet } from '../../src/types/config.types';

export const loadThresholds: ThresholdSet = {
  checks: ['rate==1'],
  http_req_duration: ['p(95)<1000', 'p(99)<2000'],
  http_req_failed: ['rate<0.02'],
  'http_req_duration{name:GET /articles}': ['p(95)<500', 'p(99)<1000'],
  'http_req_duration{name:GET /articles/:slug}': ['p(95)<500', 'p(99)<1000'],
  'http_req_duration{name:GET /articles/:slug/comments}': ['p(95)<750', 'p(99)<1500'],
  'http_req_duration{name:GET /profiles/:username}': ['p(95)<500', 'p(99)<1000'],
  'http_req_duration{name:GET /tags}': ['p(95)<300', 'p(99)<750'],
  'http_req_failed{name:GET /articles}': ['rate<0.01'],
  'http_req_failed{name:GET /articles/:slug}': ['rate<0.01'],
  'http_req_failed{name:GET /articles/:slug/comments}': ['rate<0.02'],
  'http_req_failed{name:GET /profiles/:username}': ['rate<0.01'],
  'http_req_failed{name:GET /tags}': ['rate<0.01'],
  'http_reqs{name:GET /articles}': ['count>0'],
  'http_reqs{name:GET /articles/:slug}': ['count>0'],
  'http_reqs{name:GET /articles/:slug/comments}': ['count>0'],
  'http_reqs{name:GET /profiles/:username}': ['count>0'],
  'http_reqs{name:GET /tags}': ['count>0'],
  custom_article_read_duration_ms: ['p(95)<500', 'p(99)<1000'],
  custom_article_read_success_rate: ['rate>0.99'],
  custom_comment_duration_ms: ['p(95)<750', 'p(99)<1500'],
  custom_comment_success_rate: ['rate>0.98'],
  custom_profile_duration_ms: ['p(95)<500', 'p(99)<1000'],
  custom_profile_success_rate: ['rate>0.99'],
  custom_tag_duration_ms: ['p(95)<300', 'p(99)<750'],
  custom_tag_success_rate: ['rate>0.99'],
  custom_business_errors_total: ['count<1'],
  iterations: ['rate>1'],
  dropped_iterations: ['count<10'],
  http_reqs: ['rate>5'],
};
